version: '3.8'

services:

  composer:
    build: .
    restart: "no"
    working_dir: /mod-dhl
    entrypoint: /usr/local/bin/composer.phar
    volumes:
      - .:/mod-dhl

  php:
    build: .
    restart: "no"
    volumes:
      - .:/mod-dhl
    entrypoint: ./vendor/bin/phpunit tests
    env_file:
      - .env
