name: Test

on:
  push:
    branches:
      - '**'

jobs:
  test:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout
        uses: actions/checkout@v2

      - name: Install Dependencies
        uses: php-actions/composer@v1

      - name: Test
        uses: pxgamer/phpunit-action@master
        with:
          command: tests/

