name: Test

on:
  push:
    - master
    - dev
    - upgrade-v3.1



jobs:
  test:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout
        uses: actions/checkout@v2

      - name: Install Dependencies
        uses: php-actions/composer@v1

      - name: Test
        uses: pxgamer/phpunit-action@master
        with:
          command: tests/

