name: Test

on: [ push ]

jobs:
  test:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout
        uses: actions/checkout@v2

      - name: Test
        uses: pxgamer/phpunit-action@master
        with:
          command: tests/
        env:
          API_USER: ${{ secrets.API_USER }}
          API_PASS: ${{ secrets.API_PASS }}

